import os


input_file = "../resources/full-emoji-list.txt"
output_file = "../resources/output.txt"

if os.path.exists(output_file):
    os.remove(output_file)

with open(input_file, "r", encoding="utf-8") as input, open(output_file, "w", encoding="utf-8") as output:
    emoji_lines = input.readlines()
    counter = 1
    total = 0
    error = 0
    success = 0

    output.write("// generated by " + os.path.basename(__file__))
    
    for line in emoji_lines:
        if (line.startswith("@@")):
            output.write("\n")
            output.write(line.replace("@@", "// "))
            counter = 1
            continue
        elif (line.startswith("@")):
            continue
        else:
            total += 1
            entry = line.split("\t")
            key = "".join(entry[0].split(" "))
            value = entry[1].strip().replace(" ", "_").replace(":", "")
            try:
                output.write("[\'" + chr(int(key, 16)) + "\', \'" + value + "\'], " + ("\n" if counter % 5 == 0 else ""))
                counter += 1
                success += 1
            except OverflowError:
                # OverflowError: Python int too large to convert to C int
                # C语言在Windows下long int的数据范围为-2147483647~+2147483647
                error += 1
                continue

print("total: %d, success: %d, error: %d" % (total, success, error))
